version: "3.8"

services:

  nginx:
    container_name: nginx
    build: ./docker/nginx
    command: nginx -g "daemon off;"
    links:
      - php
    ports:
      - "8080:80"
    volumes:
      - ./logs/nginx:/var/log/nginx
      - ./src:/var/www/html

  php:
    container_name: php
    user: "${UID}:${GID}"
    build: ./docker/php
    ports:
      - "9000:9000"
    volumes:
      - ./src:/var/www/html
    working_dir: /var/www/html
    env_file:
      - .env
    environment:
      PHP_MAIL_USER: ${PHP_MAIL_USER}
      PHP_MAIL_PASSWORD: ${PHP_MAIL_PASSWORD}
      HOSTNAME : ${HOSTNAME}
      DB_NAME : ${DB_NAME}
      DB_USERNAME : ${DB_USERNAME}
      PASSWORD_DB : ${PASSWORD_DB}
    stdin_open: true 
    tty: true

  mysql:
    image: mysql:8.0.27
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: 'pwddb'
      MYSQL_DATABASE: camagru_db
      MYSQL_USER: camagru_db_user
      MYSQL_PASSWORD: 'pwddb'
    ports:
      - "3306:3306"
    volumes:
      - ./database/mysql:/var/lib/mysql
      - ./init:/docker-entrypoint-initdb.d
  
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: pma
    links:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - 8085:80